language: php
dist: xenial
php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer install

script:
  - vendor/bin/phpcs --colors -p --extensions=php --standard=Submitty ./Submitty
  - vendor/bin/phpunit --filter Submitty

after_success:
    - travis_retry vendor/bin/php-coveralls